function demoOnclick() {
    alert("single clicked")
}

function demoOnDblclick() {``
    alert("double clickled")
}

function demotextFocus() {
    document.getElementById("txtFocus").style.backgroundColor = "blue"
}

function demoOnBlur() {
    document.getElementById("txtBlur").style.backgroundColor = "yellow"
}

function demoOnKeypres() {
    alert("Keypres done")
}
function demoOnKeyup() {
    alert("demoOnKeyup done")
}
